blank_issues_enabled: false
contact_links:
  - name: ğŸ‘€ Explore Discussions
    url: https://github.com/frictionlessdata/frictionless-ts/discussions
    about: Before opening a discussion, please check if the topic has already been discussed. Please vote on existing discussions to show your support.
  - name: ğŸ’¡ Feature Request
    url: https://github.com/frictionlessdata/frictionless-ts/discussions/new?category=ideas
    about: Suggest an improvement you'd like to see added to frictionless-ts
  - name: ğŸš€ Implementation
    url: https://github.com/frictionlessdata/frictionless-ts/discussions/new?category=show-and-tell
    about: Share your frictionless-ts implementation or related project with the community
  - name: ğŸ’ Question
    url: https://github.com/frictionlessdata/frictionless-ts/discussions/new?category=q-a
    about: Ask a question about frictionless-ts
